language: node_js
node_js:
  - "8.9.3"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - yarn install

script:
  - yarn test